### ISSUE TITLE
linux port

### ISSUE THREAD

**Issue by lonnietc** [can1357/simple_cnn#1]
Hello,

I was just looking over your "simple_cnn" code and noticed that it seem to be set up to compile for Windows.

I was wondering if you could port this version, or have a version that will compile up on Linux (Ubuntu) so that I do not have to dig through all of the code trying to get it to work on my Linux box?

I wanted to use your code to learn more about CNN's and how they work in a simple CPU (non-GPU) version before moving to more complex libraries.

Cheers,
Lonnie

**Comment by can1357** [comment]
I removed the Windows.h requirement from all core files. ( everything but MNIST examples pretty much )
Although I can't test it on a Linux machine/compiler, It should be working fine now.

Let me know if you have any problem compiling it on Linux.

**Comment by ujsyehao** [comment]
@can1357 how to use g++ compile it ?

**Comment by can1357** [comment]
@ujsyehao I do not know about g++ sorry.
