### ISSUE TITLE
There is no multiplication feature if two fully connected layers are there.. 

### ISSUE THREAD

**Issue by shalinsirwani** [can1357/simple_cnn#9]
I mean if there are two fully connected layer with 12 and 5 neurons.
You have to multiply weights with fully connected layer, Let say 12 x 1 layer with 12 x 5 weight matrix or tensor..  to get next layer which is 5 x 1..

**Comment by can1357** [comment]
What are you trying to say?

**Comment by shalinsirwani** [comment]
Let say if we have two fully connnected (fc_layer) layers,
1) 10 x 20 (Layer 1 dimensions)
    10 x 5 ( weight matrix dimension )
2) 5 x 20 (layer 2 dimensions)
In case of "feed forward" and "back-propagation"  we have to multiply Layer with weight matrix and with weights gradient respectively. 
So what i am trying to telling you is " in your code there is no matrix multiplication function. So how do you are performing feed forward  (AX + B) ??  "

**Comment by can1357** [comment]
https://github.com/can1357/simple_cnn/blob/master/CNN/fc_layer.h#L65
